name: bun-js
version: "1.1.27"
license: MIT
contact: https://github.com/shakeelansari63/snap-packages
issues: https://github.com/oven-sh/bun/issues
source-code: https://github.com/oven-sh/bun
website: https://bun.sh/
summary: Bun is a fast JavaScript toolkit, runtime and package manager
architectures:
  - amd64
description: |
  Develop, test, run, and bundle JavaScript & TypeScript projects—all with Bun. 
  Bun is an all-in-one JavaScript runtime & toolkit designed for speed, complete with a bundler, test runner, and Node.js-compatible package manager.

base: core22
grade: stable
confinement: strict

parts:
  bunjs:
    plugin: dump
    build-packages:
      - unzip
      - curl
      - tree
    source: .
    override-build: |
      curl https://bun.sh/install > install.sh
      chmod +x install.sh
      ./install.sh
      rm -f /root/.bun/bin/bunx
      tree /root/.bun
    organize:
      /root/.bun: _bun

apps:
  bun:
    command: _bun/bin/bun
    plugs:
      - network
      - network-bind
      - home
  bunx:
    command: _bun/bin/bun
    plugs:
      - network
      - network-bind
      - home
