name: azuredatastudio
version: "1.50.0"
license: MIT
title: Azure Data Studio
contact: https://github.com/shakeelansari63/snap-packages
website: https://azure.microsoft.com/en-in/products/data-studio
summary: A unified tooling experience for data professionals
architectures:
  - amd64
description: |
  Designed to focus on the functionality data platform developers use the most, Azure Data Studio offers additional experiences available as optional extensions. 
  It's built for data professionals who use SQL Server and Azure databases on-premises or in multicloud environments.  
    
  **Note: This is an unofficial distribution of Azure Data Studio.**

base: core22
grade: stable
confinement: strict
compression: lzo

parts:
  azuredatastudio:
    plugin: dump
    build-packages:
      - unzip
      - tar
      - curl
      - tree
    source: .
    stage-packages:
      - libxkbfile-dev
      - libssl3
      - git

    override-build: |
      # Default
      craftctl default

      # Download and add azuredatastudio
      curl -L https://azuredatastudio-update.azurewebsites.net/latest/linux-x64/stable -o ads.tgz
      tar -xf ads.tgz
      rm -rf /root/azure_data_studio
      mv ./azuredatastudio-linux-x64 /root/azure_data_studio
      rm -f ./ads.tgz

      # Fix Permission
      chmod 755 /root/azure_data_studio/chrome-sandbox

      # Copy Icon and Desktop File
      cp $SNAPCRAFT_PROJECT_DIR/static/azuredatastudio.* /root/azure_data_studio/

    override-stage: |
      # Stage
      snapcraftctl stage

      # Symblink libssl and libcrypto
      cd /usr/lib/x86_64-linux-gnu
      rm -rf libcrypto.so.10 libssl.so.10
      ln -s libcrypto.so.3 libcrypto.so.10
      ln -s libssl.so.3 libssl.so.10

    organize:
      /root/azure_data_studio: _ads

apps:
  azuredatastudio:
    extensions: ["gnome"]
    command: _ads/bin/azuredatastudio --no-sandbox
    desktop: _ads/azuredatastudio.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - browser-support
      - network
      - network-bind
      - opengl
      - home

lint:
  ignore:
    - library:
      - usr/lib/x86_64-linux-gnu/**.so*
