name: azuredatastudio
version: "1.47.0"
license: MIT
contact: https://github.com/shakeelansari63/snap-packages
website: https://azure.microsoft.com/en-in/products/data-studio
summary: A unified tooling experience for data professionals
architectures:
  - amd64
description: |
  Designed to focus on the functionality data platform developers use the most, Azure Data Studio offers additional experiences available as optional extensions. 
  It's built for data professionals who use SQL Server and Azure databases on-premises or in multicloud environments.

base: core22
grade: devel
confinement: strict

parts:
  azuredatastudio:
    plugin: dump
    build-packages:
      - unzip
      - tar
      - curl
      - tree
    source: .
    stage-packages:
      - libx11-6
      - libxcomposite-dev
      - libxdamage1
      - libxrandr2
      - libxext6
      - libxft2
      - libxrender1
      - libxss1 
    override-build: |
      curl -L https://azuredatastudio-update.azurewebsites.net/latest/linux-x64/stable -o ads.tgz
      tar -xf ads.tgz
      mv ./azuredatastudio-linux-x64 /root/azure_data_studio
      rm -f ./ads.tgz
    organize:
      /root/azure_data_studio: _ads

apps:
  azuredatastudio:
    command: desktop-launch _ads/bin/azuredatastudio
    desktop: $SNAP/meta/gui/azure.data.studio.desktop
    plugs:
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - home
