name: podman-io
version: "4.9.3-beta1"
license: Apache-2.0
contact: https://github.com/shakeelansari63/snap-packages
website: https://podman.io/
summary: The best free & open source container tools
description: |
  **Podman**  \
  Manage containers, pods, and images with Podman. \
  Seamlessly work with containers and Kubernetes from your local environment.  \
   \
  **How to Run** \
  `podman-io.podman --help` \
   \
  Want to use the `podman` command directly? run following command to create snap alias. \
  `sudo snap alias podman-io.podman podman` \
   \
  **Note: This is an unofficial distribution of Podman.**

base: core24
grade: devel
confinement: strict

environment:
  XDG_RUNTIME_DIR: ${SNAP_USER_COMMON}/

parts:
  podman:
    plugin: dump
    build-packages:
      - podman
      - uidmap
      - slirp4netns
    stage-packages:
      - podman
      - uidmap
      - slirp4netns
    source: .
apps:
  podman:
    command: /usr/bin/podman
    plugs:
      - network
      - network-bind
      - home
