name: pyenv
version: "2.3.29-beta9"
license: MIT
contact: https://github.com/shakeelansari63/snap-packages
website: https://github.com/pyenv/pyenv
summary: Simple Python Version Management
description: |
  pyenv lets you easily switch between multiple versions of Python. 
  It's simple, unobtrusive, and follows the UNIX tradition of single-purpose tools that do one thing well.
architectures:
  - amd64
base: core22
grade: stable
confinement: classic

parts:
  pyenv:
    plugin: dump
    source: https://github.com/pyenv/pyenv.git

apps:
  pyenv:
    command: bin/pyenv
    plugs:
      - network
      - network-bind
      - home
