name: php-composer
version: "0.0.1b2"
license: MIT
contact: https://github.com/shakeelansari63/snap-packages
website: https://getcomposer.org/
summary: A Dependency Manager for PHP
description: |
  **PHP and Composer**  \
  Manage PHP dependencies with Composer. \
  Seamlessly work with PHP packages from your local environment.  \
   \
  **How to Run** \
  `php-composer.composer --help` \
   \
  Want to use the `php` and `composer` commands directly? run following command to create snap alias. \
  `sudo snap alias php-composer.php php` \
  `sudo snap alias php-composer.composer composer` \
   \
  **Note: This is an unofficial distribution of PHP and Composer packaged together.**

base: core26
grade: devel
confinement: strict

environment:
  XDG_RUNTIME_DIR: ${SNAP_USER_COMMON}/

parts:
  php-composer:
    plugin: dump
    build-packages:
      - php
      - php-common
      - php-cli
      - git
      - unzip
      - curl
    stage-packages:
      - php
      - php-common
      - php-cli
      - php-mysql
      - php-pgsql
      - php-curl
      - php-xml
      - php-zip
      - php-fpm
      - php-bcmath
      - php-odbc
      - php-gd
      - php-phar
      - php-mbstring
      - git
      - unzip
      - curl
    source: .
    override-build: |
      cd ~
      curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
      HASH=$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')
      php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('/tmp/composer-setup.php'); } echo PHP_EOL;"

      # Proceed with installation
      if [[ ! -f /tmp/composer-setup.php ]]; then
        exit 1
      fi

      # Install composer
      mkdir -p /root/comp
      php /tmp/composer-setup.php --install-dir=/root/comp --filename=composer

      # Check Installed Composer versions
      /root/comp/composer --version

    override-prime: |
      # Default Prime task
      craftctl default

      # For Debug
      ls -lart $CRAFT_PRIME/

      # Symlink PHP binary
      ## Extract PHP binary from Composer
      PHP_BIN=$($CRAFT_PRIME/_comp/composer --version 2>&1 | grep /usr/bin/php | grep -oP '(?<=\()[^)]*' | sed 's#/usr/bin/##g')
      PHAR_BIN=$(echo $PHP_BIN | sed 's#php#phar#g')

      # Check if PHP binary is found and create symlink
      if [[ -n "$CRAFT_PRIME/usr/bin/$PHP_BIN" ]]; then
        echo "Found PHP binary: $PHP_BIN"
        cd $CRAFT_PRIME/usr/bin
        rm -rf php
        ln -s $PHP_BIN php
      fi

      # Check if PHP Phar binary is found and create symlink
      if [[ -n "$CRAFT_PRIME/usr/bin/$PHAR_BIN" ]]; then
        echo "Found PHP Phar binary: $PHAR_BIN"
        cd $CRAFT_PRIME/usr/bin
        rm -rf phar php.phar phar.phar
        ln -s $PHAR_BIN phar
        ln -s $PHAR_BIN php.phar
        ln -s $PHAR_BIN phar.phar
      fi

      # Create Default PHP.ini
      PHPINI_LOC=$CRAFT_PRIME$(php --ini | grep -i "php.ini" | cut -d'"' -f2 | head -1)
      PHP_INI=$PHPINI_LOC/php.ini
      echo "PHP.ini location: $PHP_INI"

      if [[ ! -f $PHP_INI ]]; then
        echo "No PHP.ini found, creating default..."

        # Find PHP's Standard ini
        find $CRAFT_PRIME/usr/lib/php -name php.ini-development -exec cp {} $PHP_INI \;
      fi

      # Update Extensions in PHP.ini
      echo "extension=phar" >> $PHP_INI
      echo "extension=mysqli" >> $PHP_INI
      echo "extension=pdo_mysql" >> $PHP_INI
      echo "extension=pgsql" >> $PHP_INI
      echo "extension=pdo_pgsql" >> $PHP_INI
      echo "extension=odbc" >> $PHP_INI
      echo "extension=pdo_odbc" >> $PHP_INI
      echo "extension=curl" >> $PHP_INI
      echo "extension=xsl" >> $PHP_INI
      echo "extension=zip" >> $PHP_INI
      echo "extension=gd" >> $PHP_INI
      echo "extension=mbstring" >> $PHP_INI
      echo "extension=fileinfo" >> $PHP_INI
      echo "extension=xml" >> $PHP_INI
      echo "extension=ftp" >> $PHP_INI
      echo "extension=gettext" >> $PHP_INI
      echo "extension=bcmath" >> $PHP_INI
      echo "extension=fpm" >> $PHP_INI

    organize:
      /root/comp: _comp

apps:
  php:
    command: usr/bin/php
    plugs:
      - network
      - network-bind
      - home
  composer:
    command: _comp/composer
    plugs:
      - network
      - network-bind
      - home
