name: Update Azure CLI on Snapcraft
on:
  push:
    branches: 
      - 'main'
    paths: 
      - 'azcli/**'

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout Branch
    steps:
      - uses: actions/checkout@v2

      - name: Build snap
        uses: snapcore/action-build@v1
        id: build
        with:
          path: azcli

      - name: Release snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
        