name: Update Bun Js on Snapcraft
on:
  push:
    branches: 
      - 'main'
    paths: 
      - bun-js.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    # Checkout Branch
    steps:
      - uses: actions/checkout@v2

      - name: Rename Bunjs to Snapcraft.yaml
        run: mv bun-js.yaml snapcraft.yaml

      - name: Build snap
        uses: snapcore/action-build@v1
        id: build

      - name: Release snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.BUN_JS_SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
        